POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "test1",
    "password": "test1"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "user",
    "name": "test user",
    "password": "pass"
}